{{- $deploymentTag := .Values.image.tag | default .Chart.AppVersion -}}
{{- $deploymentTime := now | date "2006-01-02 15:04:05.000000" -}}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "app.fullname" . }}-{{ .Values.cronjobs.analyzeuploadlogs.name }}
  labels: {{ include "app.labels" . | nindent 4 }}

spec:
  schedule: {{ .Values.cronjobs.analyzeuploadlogs.schedule }}
  concurrencyPolicy: Replace
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: log-storage
              persistentVolumeClaim:
                claimName: {{ .Values.cronjobs.analyzeuploadlogs.deployment.volumes.logs  }}
          containers:
            - resources:
                limits:
                  cpu: {{ .Values.cronjobs.analyzeuploadlogs.deployment.resources.limits.cpu  }}
                  memory: {{ .Values.cronjobs.analyzeuploadlogs.deployment.resources.limits.memory  }}
                requests:
                  cpu: {{ .Values.cronjobs.analyzeuploadlogs.deployment.resources.requests.cpu  }}
                  memory: {{ .Values.cronjobs.analyzeuploadlogs.deployment.resources.requests.memory  }}
              name: {{ include "app.fullname" . }}-{{ .Values.cronjobs.analyzeuploadlogs.name }}
              args:
                - "analyzeexportlogs"
                - "1"
              volumeMounts:
                - name: log-storage
                  mountPath: /logs
              env:
                - name: DEPLOYMENT_TAG
                  value: {{ $deploymentTag | quote }}
                - name: DEPLOYMENT_TIME
                  value: {{ $deploymentTime | quote }}
                - name: ENVIRONMENT
                  value: {{ .Values.cronjobs.analyzeuploadlogs.deployment.env.environment  }}
              envFrom:
                - secretRef:
                    name: {{ .Values.cronjobs.analyzeuploadlogs.deployment.env.s3Secret  }}
              imagePullPolicy: IfNotPresent
              image: {{ .Values.cronjobs.repository  }}:{{ .Values.cronjobs.tag  }}
              securityContext:
                seccompProfile:
                  type: 'RuntimeDefault'
                capabilities:
                  drop:
                    - all
                  add:
                    - NET_BIND_SERVICE
          restartPolicy: Never