apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "app.fullname" . }}-webcam
  labels: {{ include "app.labels" . | nindent 4 }}
{{ if .Values.route.iprestricted }}
  annotations:
    haproxy.router.openshift.io/ip_whitelist: {{ .Values.route.ipallowlist  }}
{{ end }}
spec:
  to:
    kind: Service
    name: {{ template "app.fullname" . }}
    weight: 100
  port:
    targetPort: nginx
  tls:
    termination: edge  
  host: {{ .Values.route.host  }}
  path: /webcam/


---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "app.fullname" . }}-replaytheday
  labels: {{ include "app.labels" . | nindent 4 }}
{{ if .Values.route.iprestricted }}
  annotations:
    haproxy.router.openshift.io/ip_whitelist: {{ .Values.route.ipallowlist  }}
{{ end }}
spec:
  to:
    kind: Service
    name: {{ template "app.fullname" . }}
    weight: 100
  port:
    targetPort: nginx
  tls:
    termination: edge  
  host: {{ .Values.route.host  }}
  path: /ReplayTheDay/