#!/bin/sh

echo "Updating the proxy_pass in the nginx config based on the DRIVEBC_IMAGE_BASE_URL Environment Variable"

# Display the value
echo "The value of DRIVEBC_IMAGE_BASE_URL in the environment variable is" ${DRIVEBC_IMAGE_BASE_URL}

#This will remove the trailing / if one exists as it will break the nginx.conf file
DRIVEBC_IMAGE_BASE_URL=${DRIVEBC_IMAGE_BASE_URL%/}

#Replace the $DRIVEBC_IMAGE_BASE_URL variables in the conf file.
envsubst "\${DRIVEBC_IMAGE_BASE_URL}" < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf


exec "$@"
