fullnameOverride: stg-drivebc-cache
nameOverride: stg-drivebc-cache

replicaCount: 3

image:
  repository: ghcr.io/bcgov/drivebc.ca-caching
  tag: latest-stg

deployment:
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 250m
      memory: 150Mi
  env:
    DRIVEBC_IMAGE_BASE_URL: https://stg-images.drivebc.ca/

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75

networkPolicyRequired: false  #Set to true if you need the allow traffic between pods and internet ingress setup

route:
  enabled: true
  host: stg-drivebc-cache.apps.silver.devops.gov.bc.ca
  iprestricted: false #Set to true if you want to limit IP's the the addresses in the ipallowlist below
  ipallowlist: 142.34.53.0/24 142.22.0.0/15 142.24.0.0/13 142.32.0.0/13 208.181.128.46/32 #The first 4 ranges are GOV IP's, the last one is for OXD external IP

logpvc:
  storage: 1Gi

cronjobs:
  analyzeuploadlogs:
    name: analyzeuploadlogs
    schedule: '0 9 * * *'  #NOTE: This is in UTC
    deployment:
      resources:
        requests:
          cpu: 50m
          memory: 500Mi
        limits:
          cpu: 250m
          memory: 1Gi
      env:
        s3Secret: stg-drivebc-cronjob-s3bucket
        environment: stg
      volumes:
        logs: stg-drivebc-cache-log-storage
    s3secret:
      name: stg-drivebc-cronjob-s3bucket
      access_key_id: "" #DO NOT COMMIT TO GITHUB
      bucket: ""
      endpoint: ""
      secret_access_key: "" #DO NOT COMMIT TO GITHUB

  ziplogs:
    name: ziplogs
    schedule: '0 8 * * *'
    deployment:
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          cpu: 150m
          memory: 200Mi
      volumes:
        logs: stg-drivebc-cache-log-storage