fullnameOverride: prd-drivebc-cache
nameOverride: prd-drivebc-cache

replicaCount: 3

image:
  repository: ghcr.io/bcgov/drivebc.ca-caching
  tag: latest-prd

deployment:
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 250m
      memory: 150Mi
  env:
    DRIVEBC_IMAGE_BASE_URL: https://images.drivebc.ca/

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75

networkPolicyRequired: false  #Set to true if you need the allow traffic between pods and internet ingress setup

route:
  enabled: true #Could set to false for Prd if you want to use cache.drivebc.ca exclusivly.
  host: prd-drivebc-cache.apps.silver.devops.gov.bc.ca  #NOTE: You may also have cache.drivebc.ca but that needs to be added manually as it has a certificate
  iprestricted: false #Set to true if you want to limit IP's the the addresses in the ipallowlist below
  ipallowlist: 142.34.53.0/24 142.22.0.0/15 142.24.0.0/13 142.32.0.0/13 208.181.128.46/32 #The first 4 ranges are GOV IP's, the last one is for OXD external IP

logpvc:
  storage: 5Gi

cronjobs:
  analyzeuploadlogs:
    name: analyzeuploadlogs
    schedule: '0 9 * * *'  #NOTE: This is in UTC
    deployment:
      resources:
        requests:
          cpu: 50m
          memory: 500Mi
        limits:
          cpu: 2000m
          memory: 1Gi
      env:
        s3Secret: prd-drivebc-cronjob-s3bucket
        environment: prd
      volumes:
        logs: prd-drivebc-cache-log-storage
    s3secret:
      name: prd-drivebc-cronjob-s3bucket
      access_key_id: "" #DO NOT COMMIT TO GITHUB
      bucket: ""
      endpoint: ""
      secret_access_key: "" #DO NOT COMMIT TO GITHUB

  ziplogs:
    name: ziplogs
    schedule: '30 * * * *'
    deployment:
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          cpu: 150m
          memory: 200Mi
      volumes:
        logs: prd-drivebc-cache-log-storage