fullnameOverride: prd-drivebc-cache
nameOverride: prd-drivebc-cache

replicaCount: 3

image:
  repository: ghcr.io/bcgov/drivebc.ca-caching
  tag: latest-prd

deployment:
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 250m
      memory: 150Mi
  env:
    DRIVEBC_IMAGE_BASE_URL: https://images.drivebc.ca/

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75

route:
  host: prd-drivebc-cache.apps.silver.devops.gov.bc.ca  #NOTE: You may also have cache.drivebc.ca but that needs to be added manually as it has a certificate
  iprestricted: false #Set to true if you want to limit IP's the the addresses in the ipallowlist below
  ipallowlist: 142.34.53.0/24 142.22.0.0/15 142.24.0.0/13 142.32.0.0/13 208.181.128.46/32 #The first 4 ranges are GOV IP's, the last one is for OXD external IP

