fullnameOverride: drivebc-cache
nameOverride: drivebc-cache

replicaCount: 1

image:
  repository: ghcr.io/bcgov/drivebc.ca-caching
  tag: latest

deployment:
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 250m
      memory: 100Mi
  env:
    DRIVEBC_IMAGE_BASE_URL: https://tst-images.drivebc.ca/

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

networkPolicyRequired: true  #Set to true if you need the allow traffic between pods and internet ingress setup

route:
  enabled: true
  host: drivebc-cache.apps.silver.devops.gov.bc.ca
  iprestricted: false #Set to true if you want to limit IP's the the addresses in the ipallowlist below
  ipallowlist: 142.34.53.0/24 142.22.0.0/15 142.24.0.0/13 142.32.0.0/13 208.181.128.46/32 #The first 4 ranges are GOV IP's, the last one is for OXD external IP

