fullnameOverride: dev-drivebc-cache
nameOverride: dev-drivebc-cache

replicaCount: 1

image:
  repository: ghcr.io/bcgov/drivebc.ca-caching
  tag: latest-dev

deployment:
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 250m
      memory: 150Mi
  env:
    DRIVEBC_IMAGE_BASE_URL: https://dev-images.drivebc.ca/

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 75

networkPolicyRequired: false  #Set to true if you need the allow traffic between pods and internet ingress setup

route:
  enabled: true
  host: dev-drivebc-cache.apps.silver.devops.gov.bc.ca
  iprestricted: false #Set to true if you want to limit IP's the the addresses in the ipallowlist below
  ipallowlist: 142.34.53.0/24 142.22.0.0/15 142.24.0.0/13 142.32.0.0/13 208.181.128.46/32 #The first 4 ranges are GOV IP's, the last one is for OXD external IP

logpvc:
  storage: 1Gi

cronjobs:
  image: ghcr.io/bcgov/drivebc.ca-caching-openshiftjobs
  tag:
  analyzeuploadlogs:
    name: analyzeuploadlogs
    schedule: '0 9 * * *'  #NOTE: This is in UTC
    deployment:
      resources:
        requests:
          cpu: 50m
          memory: 250Mi
        limits:
          cpu: 250m
          memory: 500Mi
      env:
        s3Secret: dev-drivebc-cronjob-s3bucket
        environment: dev
      volumes:
        logs: dev-drivebc-cache-log-storage
    s3secret:
      name: dev-drivebc-cronjob-s3bucket
      access_key_id: "" #DO NOT COMMIT TO GITHUB
      bucket: ""
      endpoint: ""
      secret_access_key: "" #DO NOT COMMIT TO GITHUB

  ziplogs:
    name: ziplogs
    schedule: '0 8 * * *'
    deployment:
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          cpu: 150m
          memory: 200Mi
      volumes:
        logs: dev-drivebc-cache-log-storage