fullnameOverride: stg-drivebc-cache
nameOverride: stg-drivebc-cache

replicaCount: 3

image:
  repository: ghcr.io/bcgov/drivebc.ca-caching
  tag: latest-stg

deployment:
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 250m
      memory: 150Mi
  env:
    DRIVEBC_IMAGE_BASE_URL: https://stg-images.drivebc.ca/

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75

networkPolicyRequired: false  #Set to true if you need the allow traffic between pods and internet ingress setup

route:
  enabled: true
  host: stg-drivebc-cache.apps.silver.devops.gov.bc.ca
  iprestricted: false #Set to true if you want to limit IP's the the addresses in the ipallowlist below
  ipallowlist: 142.34.53.0/24 142.22.0.0/15 142.24.0.0/13 142.32.0.0/13 208.181.128.46/32 #The first 4 ranges are GOV IP's, the last one is for OXD external IP

