#This will deploy the selected git tag to openshift.
name: 3. Promote from Tst to Stg

on: workflow_dispatch

env:
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}

permissions:
  packages: write

jobs:
  build-pre:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      tag: ${{ steps.vars.outputs.tag }}

    steps:
      - name: Fail on branches
        run: exit 1
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      
      - name: Remove v from version for the docker tag
        id: vars
        run: |
          vtag=${{ github.ref_name }}
          echo "tag=${vtag//v}" >> $GITHUB_OUTPUT


  deploy:
    needs: [build-pre]
    runs-on: ubuntu-latest
    name: Deploy
    environment:
      name: stg
      url: https://stg-drivebc-cache.apps.silver.devops.gov.bc.ca
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CLI tools from OpenShift Mirror
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: "4"

    - name: Add latest-stg tag to caching image
      uses: shrink/actions-docker-registry-tag@v4
      with:
        registry: ghcr.io
        repository: bcgov/drivebc.ca-caching
        target: ${{ needs.build-pre.outputs.tag }}
        tags: |
          latest-stg

    - name: Add latest-stg tag to openshiftjobs
      uses: shrink/actions-docker-registry-tag@v4
      with:
        registry: ghcr.io
        repository: bcgov/drivebc.ca-caching-openshiftjobs
        target: ${{ needs.build-pre.outputs.tag }}
        tags: |
          latest-stg

    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
        insecure_skip_tls_verify: true

    - name: Update the version in OpenShift
      run: |
        helm upgrade stg-drivebc-cache -f ./helm/values-stg.yaml ./helm --set image.tag="${{ needs.build-pre.outputs.tag }}" --set cronjobs.tag="${{ needs.build-pre.outputs.tag }}"
