name: Deploy to Dev

on:
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}


jobs:
  build-caching:
    runs-on: ubuntu-latest
    name: Build & Publish DriveBC Caching Image
    environment: dev
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Build Image Caching
      id: build_image
      uses: redhat-actions/buildah-build@v2.9
      with:
        image: drivebc.ca-caching
        tags: latest latest-dev ${{ github.sha }}
        labels: |
          app=drivebc
        containerfiles: ./compose/caching/Dockerfile
  
    - name: Push to Github Packages
      uses: redhat-actions/push-to-registry@v2.7
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}

  versionUpdate:
    needs: [build-caching]
    runs-on: ubuntu-latest
    name: Deploy Latest Image
    environment:
      name: dev
      url: https://dev-drivebc-cache.apps.silver.devops.gov.bc.ca
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
     
    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
        insecure_skip_tls_verify: true

    - name: Helm upgrade on OpenShift Environment
      run: |
        helm upgrade dev-drivebc-cache -f ./helm/values.yaml ./helm --set image.tag="${{ github.sha }}"
